// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mIXhCEeuELLjLyFbaToEANn7QN9DmO4',
    appId: '1:395359559014:web:f62e16024af59da7a7fca7',
    messagingSenderId: '395359559014',
    projectId: 'guindastes-ribasdb',
    authDomain: 'guindastes-ribasdb.firebaseapp.com',
    storageBucket: 'guindastes-ribasdb.firebasestorage.app',
    measurementId: 'G-ZN0FPERPKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlUbUH-UHJ5CY-q2xeisPPd87Vxb-8kBc',
    appId: '1:395359559014:android:b394c35f03cfc3b2a7fca7',
    messagingSenderId: '395359559014',
    projectId: 'guindastes-ribasdb',
    storageBucket: 'guindastes-ribasdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHe2vz1VxwtcbkToe9F22EvIwRQmkPsA',
    appId: '1:395359559014:ios:fa1f5eb0491dda55a7fca7',
    messagingSenderId: '395359559014',
    projectId: 'guindastes-ribasdb',
    storageBucket: 'guindastes-ribasdb.firebasestorage.app',
    iosBundleId: 'com.example.hubDigitalRibas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOHe2vz1VxwtcbkToe9F22EvIwRQmkPsA',
    appId: '1:395359559014:ios:fa1f5eb0491dda55a7fca7',
    messagingSenderId: '395359559014',
    projectId: 'guindastes-ribasdb',
    storageBucket: 'guindastes-ribasdb.firebasestorage.app',
    iosBundleId: 'com.example.hubDigitalRibas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3mIXhCEeuELLjLyFbaToEANn7QN9DmO4',
    appId: '1:395359559014:web:9bb06eb465dc253ca7fca7',
    messagingSenderId: '395359559014',
    projectId: 'guindastes-ribasdb',
    authDomain: 'guindastes-ribasdb.firebaseapp.com',
    storageBucket: 'guindastes-ribasdb.firebasestorage.app',
    measurementId: 'G-3LZRD2Y752',
  );
}
